//
// Created by Erasmo on 6/09/25.
//

#ifndef PROBARREDIRECIONAMIENTOSTANDARD_AUXILIARYFUNCTIONS_HPP
#define PROBARREDIRECIONAMIENTOSTANDARD_AUXILIARYFUNCTIONS_HPP

#include "Utils.hpp"

void to_mayus(char &c);

void read_print_str();

#endif //PROBARREDIRECIONAMIENTOSTANDARD_AUXILIARYFUNCTIONS_HPP