//
// Created by Madi on 6/10/2025.
//

#ifndef INC_2025_2_LAB05_ARREGLOS_ORDENACION_UTILS_HPP
#define INC_2025_2_LAB05_ARREGLOS_ORDENACION_UTILS_HPP
#include <iomanip>
#include <fstream>
#include <iostream>
using namespace std;
#define ANCHO_REPORTE 120
#define NRO_COLUMNAS 5
#define MAX_ETIQUETAS 105
#define MAX_CANALES 105
#define MAX_ETIQUETASENCANALES 580
#define ANCHO_TITULO1 20
#define ANCHO_TITULO2 69
//PLATAFORMA TP_Twitch
//TARIFA POR DURACION DE LAS ETIQUETAS: 0.78 POR CADA MINUTO Y FRACCION
#endif //INC_2025_2_LAB05_ARREGLOS_ORDENACION_UTILS_HPP