//
// Created by Madi on 21/09/2025.
//

#ifndef INC_252_CON_MULTIPLES__UTILS_HPP
#define INC_252_CON_MULTIPLES__UTILS_HPP
#include <iomanip>
#include <iostream>
#include <fstream>
using namespace std;
#define ANCHO_REPORTE 180
#define ANCHO_TITULO1 20
#define ANCHO_TITULO2 33
#define ANCHO_TITULO3 54
#define ANCHO_TITULO4 82
#define ANCHO_TITULO5 63
#define NRO_COLUMNAS1 7
#define NRO_COLUMNAS2 4
//PLATAFORMA TP_Twitch
//REGISTRO DE LOS CANALES AFILIADOS
//FECHAS DE CREACION ENTRE EL 10/09/2022 Y EL 01/01/2023
//TARIFA POR NUMERO DE REPRODUCCIONES: 2.57 POR CADA 1,000 REPRODUCCIONES Y FRACCION
//TARIFA POR DURACION DEL STREAM: 0.78 POR CADA MINUTO Y FRACCION
#endif //INC_252_CON_MULTIPLES__UTILS_HPP